# Generated by Django 5.2.6 on 2025-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
