# Generated by Django 5.2.6 on 2025-09-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0002_book_country_book_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extras',
            new_name='Extra',
        ),
    ]
