# Generated by Django 5.2.6 on 2025-09-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0004_alter_book_genre_alter_book_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='collections_site.extrascategory'),
        ),
    ]
