# Generated by Django 5.2.6 on 2025-09-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0005_alter_extra_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='complications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='dial_colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='movement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='numerals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='strap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
