# Generated by Django 5.2.6 on 2025-09-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0006_watch_complications_watch_dial_colour_watch_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='movement_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
