# Generated by Django 5.2.6 on 2025-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0007_watch_movement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='dial_colour',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='movement_type',
            new_name='dial',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='case_size',
            new_name='diameter',
        ),
        migrations.AddField(
            model_name='watch',
            name='winding',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
