# Generated by Django 5.2.6 on 2025-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0008_rename_dial_colour_watch_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecollection',
            name='series',
            field=models.CharField(default='', max_length=200),
        ),
    ]
