# Generated by Django 5.2.6 on 2025-09-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0009_gamecollection_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
