# Generated by Django 5.2.6 on 2025-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0010_watch_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='tracklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='complications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
