# Generated by Django 5.2.6 on 2025-09-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0011_music_tracklist_alter_watch_complications'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filmcollection',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
    ]
