# Generated by Django 5.2.6 on 2025-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0012_art_date_bought_bookcollection_date_bought_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcollection',
            name='length',
        ),
        migrations.AlterField(
            model_name='film',
            name='external_links',
            field=models.URLField(blank=True, default=list, null=True),
        ),
    ]
