# Generated by Django 5.2.6 on 2025-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0013_remove_filmcollection_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_watched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
