# Generated by Django 5.2.6 on 2025-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0014_film_date_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
