# Generated by Django 5.2.6 on 2025-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0015_book_date_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
