# Generated by Django 5.2.6 on 2025-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0017_alter_book_date_read_alter_film_date_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
