# Generated by Django 5.2.6 on 2025-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0020_book_volume_film_series_film_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='alt_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
