# Generated by Django 5.2.6 on 2025-09-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0021_film_alt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='alt_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
