# Generated by Django 5.2.6 on 2025-09-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0022_book_alt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='blurb',
            field=models.CharField(blank=True, null=True),
        ),
    ]
