# Generated by Django 5.2.6 on 2025-09-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0023_film_blurb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='owned',
        ),
    ]
