# Generated by Django 5.2.6 on 2025-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0024_remove_film_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
