# Generated by Django 5.2.6 on 2025-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0025_film_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcollection',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='filmcollection',
            name='special_features',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
