# Generated by Django 5.2.6 on 2025-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0026_filmcollection_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
