# Generated by Django 5.2.6 on 2025-09-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0027_art_notes_art_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='movement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
