# Generated by Django 5.2.6 on 2025-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0028_art_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
