# Generated by Django 5.2.6 on 2025-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0029_extra_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='theme',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
