# Generated by Django 5.2.6 on 2025-09-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0030_alter_extra_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
