# Generated by Django 5.2.6 on 2025-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0031_wardrobe_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcollection',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='printing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
