# Generated by Django 5.2.6 on 2025-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0032_bookcollection_edition_bookcollection_printing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owned',
        ),
        migrations.AddField(
            model_name='book',
            name='readlist',
            field=models.BooleanField(default=False),
        ),
    ]
