# Generated by Django 5.2.6 on 2025-09-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0033_remove_book_owned_book_readlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecollection',
            name='console',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
