# Generated by Django 5.2.6 on 2025-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0034_gamecollection_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecollection',
            name='special_tital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
