# Generated by Django 5.2.6 on 2025-09-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0035_gamecollection_special_tital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecollection',
            old_name='special_tital',
            new_name='special_title',
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='bonus_contents',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
