# Generated by Django 5.2.6 on 2025-09-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0036_rename_special_tital_gamecollection_special_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecollection',
            old_name='bonus_contents',
            new_name='bonus_content',
        ),
    ]
