# Generated by Django 5.2.6 on 2025-09-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0037_rename_bonus_contents_gamecollection_bonus_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='additional_info',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='collection',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
