# Generated by Django 5.2.6 on 2025-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0038_rename_additional_info_extra_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
