# Generated by Django 5.2.6 on 2025-09-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0039_wardrobe_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
