# Generated by Django 5.2.6 on 2025-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0040_extra_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('string', 'String'), ('keyboard', 'keyboard'), ('percussion', 'Percussion'), ('wind', 'Wind'), ('brass', 'Brass'), ('electronic', 'Electronic'), ('other', 'Other')], max_length=50)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('owned', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
