# Generated by Django 5.2.6 on 2025-09-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0041_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='maker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='materials',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
