# Generated by Django 5.2.6 on 2025-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0042_instrument_date_bought_instrument_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='industry_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='og_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='industry_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
