# Generated by Django 5.2.6 on 2025-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0043_book_industry_rating_book_og_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='industry_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='industry_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
