# Generated by Django 5.2.6 on 2025-09-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0044_alter_book_industry_rating_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
