# Generated by Django 5.2.6 on 2025-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0045_book_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition_read_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
