# Generated by Django 5.2.6 on 2025-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0046_book_edition_read_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='alt_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='alt_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
