# Generated by Django 5.2.6 on 2025-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0047_book_alt_name_film_alt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
