# Generated by Django 5.2.6 on 2025-09-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0049_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
