# Generated by Django 5.2.6 on 2025-10-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0050_alter_film_blurb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_type', models.CharField(max_length=50)),
                ('original_language', models.CharField(blank=True, max_length=100, null=True)),
                ('language_heard', models.CharField(blank=True, max_length=100, null=True)),
                ('composer', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('orchestra_ensemble', models.CharField(blank=True, max_length=255, null=True)),
                ('seen', models.BooleanField(default=True)),
                ('date_seen', models.DateField(blank=True, null=True)),
                ('location_seen', models.CharField(blank=True, max_length=255, null=True)),
                ('location_premiered', models.CharField(blank=True, max_length=255, null=True)),
                ('pieces', models.JSONField(blank=True, default=list)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('images', models.URLField(blank=True, null=True)),
                ('external_links', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
