# Generated by Django 5.2.6 on 2025-10-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0051_liveperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveperformance',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveperformance',
            name='year_specificity',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('year', 'Year'), ('decade', 'Decade'), ('century', 'Century'), ('millennium', 'Millennium'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
    ]
