# Generated by Django 5.2.6 on 2025-10-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0052_liveperformance_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveperformance',
            name='date_premiered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
