# Generated by Django 5.2.6 on 2025-10-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0053_liveperformance_date_premiered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveperformance',
            old_name='composer',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='liveperformance',
            name='alt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
