# Generated by Django 5.2.6 on 2025-10-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_site', '0054_rename_composer_liveperformance_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveperformance',
            name='writers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
